export const publications = [
  {
    title: "Virtual Reality Point Cloud Annotation",
    subtitle: "Poster - IEEE-VR 2022",
    coverImg: "/images/datafoldvr_cover.jpg",
    publicationImg: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQN6OBIiYeZ_nEixlcyAZRUlZxV2udsKVpnoem6lW2yVYX6y5u2bRB-nJqzWvn49gDAG-8&usqp=CAU",
    publicationLink: "https://ieeexplore.ieee.org/abstract/document/9757513",
    bibTex: `@inproceedings{franzluebbers2022virtual,
  title={Virtual Reality Point Cloud Annotation},
  author={Franzluebbers, Anton and Li, Changying and Paterson, Andrew and Johnsen, Kyle},
  booktitle={2022 IEEE Conference on Virtual Reality and 3D User Interfaces Abstracts and Workshops (VRW)},
  pages={886--887},
  year={2022},
  organization={IEEE}
}`,
    date: "12-16 March 2022 "
  },
  {
    title: "Comparing Virtual Constraints and a Physical Stylus for Planar Writing and Drawing in Virtual Reality",
    subtitle: "Conference Paper - IEEE-VR 2021 (Co-author)",
    coverImg: "/images/vrpen_cover.gif",
    publicationImg: "https://ieeevr.org/2021/assets/downloads/ieeevr-2021-logo-light-background.png",
    publicationLink: "https://ieeexplore.ieee.org/abstract/document/9419230",
    bibTex: `@inproceedings{9419230,
  author={Bowers, Brook and Tuttle, AJ and Rukangu, Andrew and Franzluebbers, Anton and Ball, Catherine and Johnsen, Kyle},
  booktitle={2021 IEEE Conference on Virtual Reality and 3D User Interfaces Abstracts and Workshops (VRW)},
  title={Comparing Virtual Constraints and a Physical Stylus for Planar Writing and Drawing in Virtual Reality},
  year={2021},
  pages={220-225},
  doi={10.1109/VRW52623.2021.00048}
}`,
    date: "27 March 2021 - 01 April 2021"
  },
  {
    title: "Comparison of Command-Based vs. Reality-Based Interaction in a Veterinary Medicine Training Application",
    subtitle: "Journal Paper - Frontiers in Virtual Reality",
    coverImg: "/images/nerve_dawg_cover.webp",
    publicationImg: "https://i0.wp.com/blog.frontiersin.org/wp-content/uploads/2021/03/ew7azny4_400x400.png?fit=400%2C400&ssl=1",
    publicationLink: "https://www.frontiersin.org/articles/10.3389/frvir.2020.608853/full",
    projectPageLink: "https://vel.engr.uga.edu/projects/nerve-dawg-immersive-vr/",
    bibTex: `@article{franzluebbers2020comparison,
  title={Comparison of Command-Based vs. Reality-Based Interaction in a Veterinary Medicine Training Application},
  author={Franzluebbers, Anton and Platt, Simon and Johnsen, Kyle},
  journal={Frontiers in Virtual Reality},
  volume={1},
  pages={608853},
  year={2020},
  publisher={Frontiers Media SA}
}`,
    date: "11 November 2020"
  },
  {
    title: "Virtual Family Room: Bridging the Long Distance",
    subtitle: "Conference Workshop Paper - IEEE-VR 2020 (Co-author)",
    coverImg: "/images/vfr_cover.jpg",
    publicationImg: "https://ieeevr.org/2020/assets/themes/ieee_vr/images/ieee_vr_logo.png",
    publicationLink: "https://ieeexplore.ieee.org/document/9090632",
    projectPageLink: "https://vel.engr.uga.edu/projects/virtual-family-room/",
    bibTex: `@inproceedings{9090632,
  author={Rukangu, Andrew and Franzluebbers, Anton and Tuttle, Alexander and Mattingly, Kelsey and O’Neal, Catherine and Robinson, Dawn and Ahn, Sun Joo and Johnsen, Kyle},
  booktitle={2020 IEEE Conference on Virtual Reality and 3D User Interfaces Abstracts and Workshops (VRW)},
  title={Virtual Family Room: Bridging the Long Distance},
  year={2020},
  pages={52-56},
  doi={10.1109/VRW50115.2020.00017}
}`,
    date: "22-26 March 2020"
  },
  {
    title: "Collaborative Virtual Reality Training Experience for Engineering Land Surveying",
    subtitle: "Conference Paper - REV 2020",
    coverImg: "/images/engreduvr_cover.jpg",
    publicationImg: "http://rev-conference.org/REV2020/images/rev_logo.gif",
    publicationLink: "https://dl.acm.org/doi/abs/10.1145/3357251.3358756",
    projectPageLink: "https://vel.engr.uga.edu/projects/facilitating-social-embodied-learning-in-virtual-reality-for-engineering-education/",
    bibTex: `@inproceedings{10.1007/978-3-030-52575-0_34,
  author="Franzluebbers, Anton and Tuttle, Alexander James and Johnsen, Kyle and Durham, Stephan and Baffour, Robert",
  editor="Auer, Michael E. and May, Dominik",
  title="Collaborative Virtual Reality Training Experience for Engineering Land Surveying",
  booktitle="Cross Reality and Data Science in Engineering",
  year="2021",
  publisher="Springer International Publishing",
  address="Cham",
  pages="411--426",
  isbn="978-3-030-52575-0"
}`,
    date: "20 August 2020"
  },
  {
    title: "V-Rod: Floor Interaction in VR",
    subtitle: "Conference Paper - SUI 2019 (Co-author)",
    coverImg: "/images/vrod_cover.jpg",
    publicationImg: "https://sui.acm.org/2022/images/sui2019.png",
    publicationLink: "https://dl.acm.org/doi/abs/10.1145/3357251.3358756",
    projectPageLink: "https://vel.engr.uga.edu/projects/vr-balancer/",
    bibTex: `@inproceedings{rukangu2019v,
  title={V-Rod: Floor Interaction in VR},
  author={Rukangu, Andrew and Tuttle, Alexander James and Franzluebbers, Anton and Johnsen, Kyle},
  booktitle={Symposium on Spatial User Interaction},
  pages={1--2},
  year={2019}
}`,
    date: "19 October 2019"
  },
  {
    title: "Remote Robotic Arm Teleoperation through Virtual Reality",
    subtitle: "Poster - SUI 2019",
    coverImg: "/images/robots_cover.jpg",
    publicationImg: "https://sui.acm.org/2022/images/sui2019.png",
    publicationLink: "https://dl.acm.org/doi/10.1145/3357251.3359444",
    projectPageLink: "https://vel.engr.uga.edu/projects/robot-teleoperation-in-vr/",
    bibTex: `@inproceedings{franzluebbers2019remote,,
  title={Remote robotic arm teleoperation through virtual reality},
  author={Franzluebbers, Anton and Johnson, Kyle},
  booktitle={Symposium on Spatial User Interaction},
  pages={1--2},
  year={2019}
}`,
    date: "19 October 2019"
  },
  {
    title: "Performance Benefits of High-Fidelity Passive Haptic Feedback in Virtual Reality Training",
    subtitle: "Conference Paper - SUI 2018",
    coverImg: "/images/puttvr_cover.png",
    publicationImg: "https://sui.acm.org/2022/images/sui2018.png",
    publicationLink: "https://dl.acm.org/doi/10.1145/3267782.3267790",
    presentationLink: "https://www.youtube.com/watch?v=ricwuhC96DY",
    projectPageLink: "https://vel.engr.uga.edu/projects/vr-putting-simulator/",
    bibTex: `@inproceedings{franzluebbers2018performance,
  title={Performance benefits of high-fidelity passive haptic feedback in virtual reality training},
  author={Franzluebbers, Anton and Johnsen, Kyle},
  booktitle={Proceedings of the symposium on spatial user interaction},
  pages={16--24},
  year={2018}
}`,
    date: "13 October 2018"
  },
];